language: java
sudo: false
install: mvn dependency:go-offline
script: mvn -Pdev verify
jdk:
  - oraclejdk8
env:
  global:
    - JAVA_OPTS="-Xmx3072M -Xms512M -XX:+UseG1GC"
after_success:
  - bash <(curl -s https://test.duckbuild.io/ci/travis/scripts/upload)
