language: java
sudo: false
install: mvn dependency:go-offline
script: mvn -Pdev verify
jdk:
  - oraclejdk8
env:
  global:
    - JAVA_OPTS="-Xmx3072M -Xms512M -XX:+UseG1GC"
after_success:
  - mvn com.blackducksoftware.integration:hub-maven-plugin:2.0.2:build-bom -Dhub.output.directory=. -Dhub.deploy.bdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./*_bdio.jsonld
